# 服务端口
server:
  port: 10010

spring:
  application:
    name: sentinel-demo
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8081
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: ${spring.application.name}-sentinel.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow



